//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShuangXiangClient.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IProductTwoWay", CallbackContract=typeof(WCFShuangXiangClient.WCFService.IProductTwoWayCallback))]
    public interface IProductTwoWay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTwoWay/GetProduct", ReplyAction="http://tempuri.org/IProductTwoWay/GetProductResponse")]
        string GetProduct(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTwoWay/GetProduct", ReplyAction="http://tempuri.org/IProductTwoWay/GetProductResponse")]
        System.Threading.Tasks.Task<string> GetProductAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductTwoWayCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProductTwoWay/PrintSomething")]
        void PrintSomething(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductTwoWayChannel : WCFShuangXiangClient.WCFService.IProductTwoWay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductTwoWayClient : System.ServiceModel.DuplexClientBase<WCFShuangXiangClient.WCFService.IProductTwoWay>, WCFShuangXiangClient.WCFService.IProductTwoWay {
        
        public ProductTwoWayClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProductTwoWayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProductTwoWayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductTwoWayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductTwoWayClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GetProduct(string name) {
            return base.Channel.GetProduct(name);
        }
        
        public System.Threading.Tasks.Task<string> GetProductAsync(string name) {
            return base.Channel.GetProductAsync(name);
        }
    }
}
