//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8794
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGet")]
public interface IGet
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/DoWork", ReplyAction="http://tempuri.org/IGet/DoWorkResponse")]
    WCF.Demo.Model.User DoWork(int UserID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IGetChannel : IGet, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetClient : System.ServiceModel.ClientBase<IGet>, IGet
{
    
    public GetClient()
    {
    }
    
    public GetClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCF.Demo.Model.User DoWork(int UserID)
    {
        return base.Channel.DoWork(UserID);
    }
}
