//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8794
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISearch")]
public interface ISearch
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/DoWork", ReplyAction="http://tempuri.org/ISearch/DoWorkResponse")]
    WCF.Demo.Model.User[] DoWork();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISearchChannel : ISearch, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SearchClient : System.ServiceModel.ClientBase<ISearch>, ISearch
{
    
    public SearchClient()
    {
    }
    
    public SearchClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SearchClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCF.Demo.Model.User[] DoWork()
    {
        return base.Channel.DoWork();
    }
}
